name: Pre-commit Check

on:
  pull_request:
  push:
    branches:
      - "main"
  # on demand
  workflow_dispatch:    

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uvx pre-commit run --all-files --show-diff-on-failure --color=always
